Repository skycoin/hardware-wallet-go, pull requests merged in 2019-03, with the labels that each got.

#63 Refactor api to make it more testeable - fixes #62
  .gitignore
  .travis.yml
  Makefile
  src/cli/address_gen.go
  src/cli/apply_settings.go
  src/cli/backup.go
  src/cli/cancel.go
  src/cli/check_message_signature.go
  src/cli/features.go
  src/cli/firmware_update.go
  src/cli/generate_mnemonic.go
  src/cli/recovery.go
  src/cli/sandbox.go
  src/cli/set_mnemonic.go
  src/cli/set_pin_code.go
  src/cli/sign_message.go
  src/cli/transaction_sign.go
  src/cli/wipe.go
  src/device-wallet/device-wallet.go
  src/device-wallet/device_interface_test.go
  src/device-wallet/helper.go
  src/device-wallet/messages.go
  src/device-wallet/mocks/.gitkeep
Labels: stdev, wip

#67 refs #36 - ToC and development guidelines in README
  README.md
Labels: stdev, wip

#78 fixes #77 - Do not cancel check signature commands
  .travis.yml
  README.md
  src/device-wallet/messages.go
Labels: Milestone 1.0.0, stdev, wip

#80 fixes #79 - Protobuff changes related to PR (if any)
  .github/pull_request_template.md
Labels: stdev, wip

#76 resent generate mnemonic after a entropy ack required by a generate mnemonic msg ref #73
  src/device-wallet/device-wallet.go
  src/device-wallet/device_wallet_test.go
Labels: Milestone 1.0.0, stdev, wip

#81 fixes #79 - Blank issue template
  .github/ISSUE_TEMPLATE/blank.md
Labels: stdev, wip

#82 refs #36 - Update changelog before v1
  CHANGELOG.md
Labels: Milestone v.1.0.0, stdev, wip
