Repository skycoin/hardware-wallet-go, pull requests merged in 2019-05, with the labels that each got.

#118 Firmware feature test ref #117
  CHANGELOG.md
  Gopkg.lock
  Gopkg.toml
  src/cli/features.go
  src/device-wallet/bit_encoded_flags.go
  src/device-wallet/bit_encoded_flags_test.go
  src/device-wallet/device_wallet_test.go
  src/device-wallet/integration/device_interface_test.go
  vendor/github.com/skycoin/hardware-wallet-protob/go/google/protobuf/descriptor.pb.go
  vendor/github.com/skycoin/hardware-wallet-protob/go/messages.pb.go
  vendor/github.com/skycoin/hardware-wallet-protob/go/types.pb.go
Labels: Milestone v.1.0.0, stdev, wip

#121 Release pipe line ref #119
  .travis.yml
  CHANGELOG.md
  Makefile
  VERSION
  ci-scripts/version.sh
Labels: Milestone v.1.0.0, ci, stdev, wip

#126 Refactor tests
  .golangci.yml
  .travis.yml
  CHANGELOG.md
  Gopkg.lock
  Makefile
  ci-scripts/integration-test.sh
  src/cli/address_gen.go
  src/cli/apply_settings.go
  src/cli/backup.go
  src/cli/cancel.go
  src/cli/check_message_signature.go
  src/cli/cli.go
  src/cli/features.go
  src/cli/firmware_update.go
  src/cli/generate_mnemonic.go
  src/cli/get_mixed_entropy.go
  src/cli/get_raw_entropy.go
  src/cli/integration/empty.go
  src/cli/integration/integration_test.go
  src/cli/recovery.go
  src/cli/remove_pin_code.go
  src/cli/sandbox.go
  src/cli/set_mnemonic.go
  src/cli/set_pin_code.go
  src/cli/sign_message.go
  src/cli/transaction_sign.go
  src/cli/usbhid.go
  src/cli/wipe.go
  src/skywallet/bit_encoded_flags.go
  src/skywallet/bit_encoded_flags_test.go
  src/skywallet/helper.go
  src/skywallet/integration/device_interface_test.go
  src/skywallet/messages.go
  src/skywallet/mock_device_driver_test.go
  src/skywallet/mock_devicer_test.go
  src/skywallet/progress_bar.go
  src/skywallet/skywallet.go
  src/skywallet/skywallet_test.go
Labels: Milestone v.1.0.0

#129 Entropy Ack
  src/skywallet/helper.go
  src/skywallet/skywallet.go
  src/skywallet/skywallet_test.go
Labels: Milestone v.1.0.0
