Repository skycoin/hardware-wallet-go, pull requests merged in 2019-04, with the labels that each got.

#68 refs #36 - Run hardware wallet emulator on Travis CI builds
  .travis.yml
  CHANGELOG.md
  Makefile
  ci-scripts/install-linux.sh
  ci-scripts/install-osx.sh
  src/cli/address_gen.go
  src/cli/backup.go
  src/cli/set_pin_code.go
  src/device-wallet/device-wallet.go
  src/device-wallet/device_wallet_test.go
  src/device-wallet/helper.go
  src/device-wallet/integration/device_interface_test.go
  src/device-wallet/messages.go
Labels: ci, stdev, wip

#89 Problem to update firmware ref #88
  src/device-wallet/device-wallet.go
Labels: Milestone v.1.0.0, stdev, wip

#112 Fixes #106 Document firmware features
  cmd/cli/README.md
Labels: Milestone v.1.0.0, doc, stdev, wip
